///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ranorex_bdd
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ranorex_bddRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("8e9a327c-eb57-46bf-98c4-919f533fb40f")]
    public partial class ranorex_bddRepository : RepoGenBaseFolder
    {
        static ranorex_bddRepository instance = new ranorex_bddRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ranorex_bddRepository element repository.
        /// </summary>
        [RepositoryFolder("8e9a327c-eb57-46bf-98c4-919f533fb40f")]
        public static ranorex_bddRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ranorex_bddRepository() 
            : base("ranorex_bddRepository", "/", null, 0, false, "8e9a327c-eb57-46bf-98c4-919f533fb40f", ".\\RepositoryImages\\ranorex_bddRepository8e9a327c.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8e9a327c-eb57-46bf-98c4-919f533fb40f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class ranorex_bddRepositoryFolders
    {
    }
#pragma warning restore 0436
}